### ISSUE TITLE
InfluxDB Harvester: exception on time formatting

### ISSUE THREAD

**Issue by justb4** [smartemission/docker-se-stetl#1]
Only happens in some cases;

```
Status: Downloaded newer image for smartemission/se-stetl:1.0.1
entry.sh: OK using config file: config/harvester_influx.cfg...
2018-05-01 17:10:15,987 util INFO Found cStringIO, good!
2018-05-01 17:10:16,055 util INFO Found lxml.etree, native XML parsing, fabulous!
2018-05-01 17:10:16,122 util INFO Found GDAL/OGR Python bindings, super!!
2018-05-01 17:10:16,129 main INFO Stetl version = 1.2-dev
2018-05-01 17:10:16,130 main INFO Found args file at: options/default.args
2018-05-01 17:10:16,133 ETL INFO INIT - Stetl version is 1.2-dev
2018-05-01 17:10:16,133 ETL INFO Config/working dir = /work/config
2018-05-01 17:10:16,133 ETL INFO Reading config_file = config/harvester_influx.cfg
2018-05-01 17:10:16,133 ETL INFO Substituting 84 args in config file from args_dict
2018-05-01 17:10:16,133 ETL INFO Substituting args OK
2018-05-01 17:10:16,134 ETL INFO START
2018-05-01 17:10:16,134 util INFO Timer start: total ETL
2018-05-01 17:10:16,134 chain INFO Assembling Chain: input_influxdb_1|output_postgres_insert...
2018-05-01 17:10:16,426 input INFO cfg = {'progress_table': 'harvester_progress', 'max_proc_time_secs': '660', 'database': 'airsenseur', 'device_version': '1', 'pg_password': '', 'meas_name_to_device_id': "{'Geonovum1': '11810001', 'JustObjects1': '11810002'}", 'device_type': 'ase', 'port': '8086', 'pg_schema': 'smartem_raw', 'host': 'influxdb', 'pg_port': '5432', 'user': '', 'content_type': 'application/x-www-form-urlencoded', 'pg_database': 'gis', 'password': '', 'pg_user': 'docker', 'class': 'smartem.harvester.harvestinfluxdb.HarvesterInfluxDbInput', 'pg_host': 'postgis'}
2018-05-01 17:10:16,427 output INFO cfg = {'input_format': 'record_array', 'database': 'gis', 'replace': 'True', 'host': 'postgis', 'user': '', 'key': 'unique_id', 'table': 'timeseries', 'password': 'docker', 'class': 'outputs.dboutput.PostgresInsertOutput', 'schema': 'smartem_raw'}
2018-05-01 17:10:16,427 chain INFO Running Chain: input_influxdb_1|output_postgres_insert
2018-05-01 17:10:16,427 InfluxDbInput INFO Setting up connection to influxdb influxdb:8086, database=airsenseur
2018-05-01 17:10:16,428 postgis INFO Connecting to dbname=gis user=docker host=postgis port=5432
2018-05-01 17:10:16,438 postgis DEBUG Connected to database gis
2018-05-01 17:10:16,439 InfluxDbInput INFO Querying database: SHOW MEASUREMENTS
2018-05-01 17:10:16,441 InfluxDbInput INFO Received 2 results
2018-05-01 17:10:16,441 InfluxDbInput INFO Querying database: SHOW FIELD KEYS FROM Geonovum1
2018-05-01 17:10:16,443 InfluxDbInput INFO Received 8 results
2018-05-01 17:10:16,443 InfluxDbInput INFO Querying database: SELECT FIRST(altitude), time FROM Geonovum1
2018-05-01 17:10:16,446 InfluxDbInput INFO Received 1 results
2018-05-01 17:10:16,447 InfluxDbInput INFO Querying database: SHOW FIELD KEYS FROM Geonovum1
2018-05-01 17:10:16,448 InfluxDbInput INFO Received 8 results
2018-05-01 17:10:16,448 InfluxDbInput INFO Querying database: SELECT LAST(altitude), time FROM Geonovum1
2018-05-01 17:10:16,451 InfluxDbInput INFO Received 1 results
2018-05-01 17:10:16,453 InfluxDbInput INFO Querying database: SHOW FIELD KEYS FROM JustObjects1
2018-05-01 17:10:16,454 InfluxDbInput INFO Received 8 results
2018-05-01 17:10:16,454 InfluxDbInput INFO Querying database: SELECT FIRST(altitude), time FROM JustObjects1
2018-05-01 17:10:16,459 InfluxDbInput INFO Received 1 results
2018-05-01 17:10:16,459 InfluxDbInput INFO Querying database: SHOW FIELD KEYS FROM JustObjects1
2018-05-01 17:10:16,461 InfluxDbInput INFO Received 8 results
2018-05-01 17:10:16,461 InfluxDbInput INFO Querying database: SELECT LAST(altitude), time FROM JustObjects1
2018-05-01 17:10:16,465 InfluxDbInput INFO Received 1 results
Traceback (most recent call last):
  File "/usr/local/bin/stetl", line 4, in <module>
    __import__('pkg_resources').run_script('Stetl==1.2.dev0', 'stetl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Stetl-1.2.dev0-py2.7.egg/EGG-INFO/scripts/stetl", line 40, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/Stetl-1.2.dev0-py2.7.egg/EGG-INFO/scripts/stetl", line 31, in main
    etl.run()
  File "/usr/local/lib/python2.7/dist-packages/Stetl-1.2.dev0-py2.7.egg/stetl/etl.py", line 154, in run
    chain.run()
  File "/usr/local/lib/python2.7/dist-packages/Stetl-1.2.dev0-py2.7.egg/stetl/chain.py", line 164, in run
    self.first_comp.do_init()
  File "/usr/local/lib/python2.7/dist-packages/Stetl-1.2.dev0-py2.7.egg/stetl/component.py", line 212, in do_init
    self.init()
  File "/work/smartem/harvester/harvestinfluxdb.py", line 191, in init
    current_ts = self.date_str_to_whole_hour_nanos(date_str)
  File "/work/smartem/harvester/harvestinfluxdb.py", line 241, in date_str_to_whole_hour_nanos
    timestamp = self.date_str_to_ts_nanos(date_str)
  File "/work/smartem/influxdbinput.py", line 83, in date_str_to_ts_nanos
    '%Y-%m-%dT%H:%M:%S.%f%Z'
  File "/usr/lib/python2.7/_strptime.py", line 478, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2018-01-31T24:00:00.000GMT' does not match format '%Y-%m-%dT%H:%M:%S.%f%Z'

```

**Comment by justb4** [comment]
Fixed, close.
